/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui {
    export class MainSceneUI extends View {
		public input:Laya.TextInput;
		public selectBtn:Laya.Button;
		public cb1:Laya.ComboBox;
		public box:Laya.Box;
        public static  uiView:any ={"type":"View","props":{"width":750,"height":1200},"compId":2,"child":[{"type":"TextInput","props":{"y":3,"x":246,"width":77,"var":"input","text":"2019-07-30","skin":"comp/textinput.png","scaleY":2,"scaleX":2,"height":22},"compId":4},{"type":"Button","props":{"y":1.5,"x":419,"width":80,"var":"selectBtn","skin":"comp/button.png","label":"查看"},"compId":5},{"type":"ComboBox","props":{"y":0,"x":0,"width":232,"var":"cb1","skin":"comp/combobox.png","selectedIndex":0,"labels":"超强脑洞","labelSize":26,"height":50},"compId":12},{"type":"Box","props":{"y":110,"x":0,"width":750,"var":"box","height":1022},"compId":13}],"loadList":["comp/textinput.png","comp/button.png","comp/combobox.png"],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(MainSceneUI.uiView);
        }
    }
    REG("ui.MainSceneUI",MainSceneUI);
    export class txtCellUI extends View {
		public idTxt:Laya.Label;
		public strTxt:Laya.Label;
		public countTxt:Laya.Label;
        public static  uiView:any ={"type":"View","props":{"width":750,"height":25},"compId":2,"child":[{"type":"Label","props":{"y":0,"x":0,"width":93,"var":"idTxt","text":"label","height":25,"fontSize":24,"color":"#f4efef"},"compId":3},{"type":"Label","props":{"y":0,"x":130,"width":419,"var":"strTxt","text":"label","height":25,"fontSize":24,"color":"#f4efef"},"compId":4},{"type":"Label","props":{"y":0,"x":575,"width":100,"var":"countTxt","text":"label","height":25,"fontSize":24,"color":"#f4efef"},"compId":5}],"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(txtCellUI.uiView);
        }
    }
    REG("ui.txtCellUI",txtCellUI);
}